.ifndef SPOTLIGHT_PUZZLE_CONSTANTS_INC
SPOTLIGHT_PUZZLE_CONSTANTS_INC = 1

SPOTLIGHT_DISTANCE = 10

SPOTLIGHT_PUZZLE_PARAMS = 1

spotlight_puzzle_flags_mask = entity_local0
spotlight_index0 = entity_local1
spotlight_index1 = entity_local2
anglerfish_index0 = entity_local3
anglerfish_index1 = entity_local4

.enum
SPOTLIGHT_PUZZLE_STATE_INIT
SPOTLIGHT_PUZZLE_STATE_MAIN
.endenum

.endif
