.ifndef SWITCH_PUZZLE_CONSTANTS_INC
SWITCH_PUZZLE_CONSTANTS_INC = 1

SWITCH_PUZZLE_VICTORY_PAUSE = 120

.enum
SWITCH_PUZZLE_STATE_INIT
SWITCH_PUZZLE_STATE_MAIN
SWITCH_PUZZLE_STATE_VICTORY
.endenum

SWITCH_PUZZLE_PARAMS = 4

switch_puzzle_entity_dungeon_flags_mask = entity_local0
switch_puzzle_treasure_chest_type = entity_local1
switch_puzzle_treasure_chest_quantity_lo = entity_local2
switch_puzzle_treasure_chest_quantity_hi = entity_local3

switch_puzzle_state_counter = entity_local4

.endif
