.ifndef INVENTORY_SPRITES_AND_ANIMATIONS_INC
INVENTORY_SPRITES_AND_ANIMATIONS_INC = 1

cursor0:
  .byte $08
  .byte $f8,$00,$01,$f8,$10
  .byte $f8,$01,$01,$00,$08
  .byte $f8,$02,$01,$08,$00
  .byte $00,$05,$01,$f8,$10
  .byte $00,$06,$01,$08,$00
  .byte $08,$07,$01,$f8,$10
  .byte $08,$08,$01,$00,$08
  .byte $08,$09,$01,$08,$00
radio0:
  .byte $01
  .byte $00,$03,$01,$00,$00

.endif
