.ifndef INVENTORY_SPRITES_AND_ANIMATIONS_INC
INVENTORY_SPRITES_AND_ANIMATIONS_INC = 1

Cursor0:
  .byte $09
  .byte $f8,$00,$00,$f8,$10
  .byte $f8,$01,$00,$00,$08
  .byte $f8,$02,$00,$08,$00
  .byte $00,$03,$00,$f8,$10
  .byte $00,$04,$00,$00,$08
  .byte $00,$05,$00,$08,$00
  .byte $08,$06,$00,$f8,$10
  .byte $08,$07,$00,$00,$08
  .byte $08,$08,$00,$08,$00
Radio0:
  .byte $01
  .byte $00,$09,$00,$00,$00
Tech1_Selector:
  .byte $01
  .byte $00,$0a,$00,$00,$00
Tech2_Selector:
  .byte $01
  .byte $00,$0b,$00,$00,$00

.endif
