.ifndef BG_CHR_DATA_INC
BG_CHR_DATA_INC = 1

BG_CHR_DATA_BANK1 = 9
BG_CHR_DATA_BANK2 = 10
BG_CHR_DATA_BANK3 = 11
BG_CHR_DATA_BANK4 = 25
BG_CHR_DATA_BANK5 = 26

.global textbox_chr
.global font_chr
.global punctuation_chr
.global digits_chr
.global underscore_chr
.global map0_chr
.global house1_chr
.global meadow1_trees
.global meadow1_grass
.global meadow1_flowers
.global meadow1_trees_corners
.global meadow_dungeon1_entrance
.global dungeon1_main_chr
.global dungeon1_pool_chr
.global dungeon1_stones_chr
.global tundra_chr
.global dungeon2_main_chr
.global dungeon2_platform_chr
.global mountain_chr
.global cave_chr
.global dungeon3_main_chr
.global shore_chr
.global palm_trees_chr
.global sand_chr
.global temple_chr
.global dungeon4_main_chr
.global piratebay_chr
.global piratetavern_main_chr
.global piratetavern_door_chr
.global piratetavern_objects_chr
.global piratetavern_shooting_gallery_chr
.global submarine_chr
.global tortoise_chr
.global gradual_games_logo_chr
.global inventory_bg_chr
.global title_chr
.global intro_cut_scene_great_owls_bg_chr
.global intro_cut_scene_mermon_bg_chr
.global intro_cut_scene_mermon_mad_bg_chr
.global intro_cut_scene_mermon_leer_bg_chr
.global intro_cut_scene_silmaran_bg_chr

.endif
