.ifndef BG_CHR_DATA_INC
BG_CHR_DATA_INC = 1

BG_CHR_DATA_BANK1 = 8
BG_CHR_DATA_BANK2 = 9

.global textbox_chr
.global digits_chr
.global map0_chr
.global house1_chr
.global meadow1_trees
.global meadow1_grass
.global meadow1_flowers
.global meadow1_trees_corners
.global meadow_dungeon1_entrance
.global dungeon1_main_chr
.global dungeon1_pool_chr
.global inventory_chr
.global title_chr
.global game_over_chr
.global intro_cut_scene_slide1_bg_chr

.endif
