.ifndef BG_CHR_DATA_INC
BG_CHR_DATA_INC = 1

BG_CHR_DATA_BANK1 = 8
BG_CHR_DATA_BANK2 = 9

.global textbox_chr
.global font_chr
.global punctuation_chr
.global digits_chr
.global underscore_chr
.global map0_chr
.global house1_chr
.global meadow1_trees
.global meadow1_grass
.global meadow1_flowers
.global meadow1_trees_corners
.global meadow_dungeon1_entrance
.global dungeon1_main_chr
.global dungeon1_pool_chr
.global dungeon1_stones_chr
.global inventory_bg_chr
.global title_chr
.global game_over_chr
.global intro_cut_scene_great_owls_bg_chr
.global intro_cut_scene_mermon_bg_chr
.global intro_cut_scene_mermon_mad_bg_chr
.global intro_cut_scene_mermon_leer_bg_chr
.global intro_cut_scene_silmaran_bg_chr

.endif
