.ifndef FAMILIAR_INC
FAMILIAR_INC = 1

.global familiar_init
.global familiar_spawn_rush
.global familiar_spawn_fetch
.global familiar_spawn_carry_bomb
.global familiar_spawn_carry_hero
.global familiar_spawn_nop
.global align_familiar_if_occluded_by_textbox
.global familiar_calculate_screen_coordinates
.global familiar_draw
.global familiar_update
.global familiar_fetch_return_to_hero
.global familiar_hit_enemy

.endif
