.ifndef FAMILIAR_INC
FAMILIAR_INC = 1

.global familiar_module_init
.global familiar_spawn_rush
.global familiar_spawn_fetch
.global familiar_spawn_unlock
.global familiar_spawn_carry_bomb
.global familiar_spawn_carry_lantern
.global familiar_spawn_carry_hero
.global familiar_spawn_shield
.global familiar_spawn_homing
.global familiar_spawn_nop
.global align_familiar_if_occluded_by_textbox
.global familiar_calculate_screen_coordinates
.global familiar_draw
.global familiar_draw_shadow_spot
.global familiar_update
.global familiar_fetch_item
.global familiar_hit_enemy
.global familiar_common_init
.global familiar_play_flap_sound

.endif
