.ifndef MAP_DATA_INC
MAP_DATA_INC = 1

.global palette
.global map0_chr
.global map
.global big_metatile_table_bottom_right
.global big_metatile_table_bottom_left
.global big_metatile_table_top_right
.global big_metatile_table_top_left
.global metatile_table_bottom_right_tiles
.global metatile_table_bottom_left_tiles
.global metatile_table_top_right_tiles
.global metatile_table_top_left_tiles
.global metatile_table_attributes

.endif
