.ifndef MAP_DATA_INC
MAP_DATA_INC = 1

.global village_palette
.global village_map
.global village_big_metatile_table_bottom_right
.global village_big_metatile_table_bottom_left
.global village_big_metatile_table_top_right
.global village_big_metatile_table_top_left
.global village_metatile_table_properties
.global village_metatile_table_params
.global village_metatile_table_attributes
.global village_metatile_table_bottom_right_tiles
.global village_metatile_table_bottom_left_tiles
.global village_metatile_table_top_right_tiles
.global village_metatile_table_top_left_tiles

.global house1_palette
.global house1_map
.global house1_big_metatile_table_bottom_right
.global house1_big_metatile_table_bottom_left
.global house1_big_metatile_table_top_right
.global house1_big_metatile_table_top_left
.global house1_metatile_table_properties
.global house1_metatile_table_params
.global house1_metatile_table_attributes
.global house1_metatile_table_bottom_right_tiles
.global house1_metatile_table_bottom_left_tiles
.global house1_metatile_table_top_right_tiles
.global house1_metatile_table_top_left_tiles

.global inn_palette
.global inn_map
.global inn_big_metatile_table_bottom_right
.global inn_big_metatile_table_bottom_left
.global inn_big_metatile_table_top_right
.global inn_big_metatile_table_top_left
.global inn_metatile_table_properties
.global inn_metatile_table_params
.global inn_metatile_table_attributes
.global inn_metatile_table_bottom_right_tiles
.global inn_metatile_table_bottom_left_tiles
.global inn_metatile_table_top_right_tiles
.global inn_metatile_table_top_left_tiles

.global overworld_palette
.global overworld_map
.global overworld_big_metatile_table_bottom_right
.global overworld_big_metatile_table_bottom_left
.global overworld_big_metatile_table_top_right
.global overworld_big_metatile_table_top_left
.global overworld_metatile_table_properties
.global overworld_metatile_table_params
.global overworld_metatile_table_attributes
.global overworld_metatile_table_bottom_right_tiles
.global overworld_metatile_table_bottom_left_tiles
.global overworld_metatile_table_top_right_tiles
.global overworld_metatile_table_top_left_tiles

.endif
