.ifndef MUSIC_DATA_INC
MUSIC_DATA_INC = 1

.global hero_theme
.global logo_theme
.global forest_theme
.global tundra_theme
.global piratebay_theme
.global dungeon_theme
.global octoboss_theme
.global town_theme
.global game_over
.global title_theme
.global silmaran_theme
.global defeat_boss
.global game_menu_theme
.global submarine_ambience
.global mermon_fortress_theme
.global mermon_dungeon_theme
.global final_boss_theme
.global ending_theme

.endif
