.ifndef NAMETABLE_DATA_INC
NAMETABLE_DATA_INC = 1

NAMETABLE_DATA_BANK1 = 12

.global gradual_games_logo_screen
.global inventory_screen
.global title_screen
.global intro_cut_scene_great_owls_nametable
.global intro_cut_scene_mermon_nametable
.global intro_cut_scene_mermon_mad_nametable
.global intro_cut_scene_mermon_leer_nametable
.global intro_cut_scene_silmaran_nametable
.global end_cut_scene_slide1_nametable
.global end_cut_scene_slide2_nametable
.global end_cut_scene_slide3_nametable

.endif
