.ifndef SFX_DATA_INC
SFX_DATA_INC = 1

SFX_BANK = 6

.global sfx_volume_envelopes
.global sfx_pitch_envelopes
.global sfx_duty_envelopes

.global sfx_set1
.global sfx_test
.global sfx_hit
.global sfx_sword
.global sfx_door
.global sfx_flap
.global sfx_explosion
.global sfx_text
.global sfx_get_item
.global sfx_move_cursor
.global sfx_select
.global sfx_inventory
.global sfx_error
.global sfx_door_slam
.global sfx_monolith_slam
.global sfx_chest_open
.global sfx_chest_melody
.global sfx_solved_puzzle_instrument_one
.global sfx_solved_puzzle_instrument_two
.global sfx_octoboss_rise
.global sfx_octoboss_punch
.global sfx_ice_shatter_square
.global sfx_ice_shatter_noise

.endif
