.ifndef SFX_DATA_INC
SFX_DATA_INC = 1

SFX_BANK = 4

.global sfx_volume_envelopes
.global sfx_pitch_envelopes
.global sfx_duty_envelopes

.global sfx_set1
.global sfx_test
.global sfx_hit
.global sfx_sword
.global sfx_door
.global sfx_flap
.global sfx_explosion
.global sfx_text
.global sfx_get_item
.global sfx_move_cursor
.global sfx_select
.global sfx_inventory
.global sfx_error
.global sfx_door_slam
.global sfx_monolith_slam
.global sfx_chest_open
.global sfx_chest_melody

.endif
