.ifndef SPRITE_CHR_INC
SPRITE_CHR_INC = 1

SPRITE_CHR_DATA_BANK = 8

.global sprite_chr_group_addresses_lo
.global sprite_chr_group_addresses_hi
.global sprite_chr_group_bank

.enum
sprite_chr_group_index_hero
sprite_chr_group_index_rushtech
sprite_chr_group_index_fetchtech
sprite_chr_group_index_unlocktech
sprite_chr_group_index_bombtech
sprite_chr_group_index_lanterntech
sprite_chr_group_index_carrytech
sprite_chr_group_index_shieldtech
sprite_chr_group_index_homingtech
sprite_chr_group_index_familiar
sprite_chr_group_index_tyto
sprite_chr_group_index_explosion
sprite_chr_group_index_shadowspot
sprite_chr_group_index_bomb
sprite_chr_group_index_octopus
sprite_chr_group_index_npcman
sprite_chr_group_index_npcwoman
sprite_chr_group_index_key
sprite_chr_group_index_treasure_chest
sprite_chr_group_index_cursor
sprite_chr_group_index_lantern
sprite_chr_group_index_coins
sprite_chr_group_index_title
sprite_chr_group_index_pufferfish
sprite_chr_group_index_crab
sprite_chr_group_index_anglerfish
sprite_chr_group_index_spotlight
sprite_chr_group_index_octoboss
sprite_chr_group_index_splash
sprite_chr_group_index_silmaran
sprite_chr_group_index_greathornedowl
sprite_chr_group_index_cage
sprite_chr_group_index_dungeon_entrance_statue
sprite_chr_group_index_eel
sprite_chr_group_index_jellyfish
sprite_chr_group_index_urchin
sprite_chr_group_index_ice_shards
sprite_chr_group_index_ice_block
sprite_chr_group_index_swordfish_boss
sprite_chr_group_index_siberianeagleowl
sprite_chr_group_index_horseshoe_crab
sprite_chr_group_index_seahorse
sprite_chr_group_index_intro_cut_scene_great_owls
sprite_chr_group_index_intro_cut_scene_mermon_leer
.endenum

sprite_chr_group_bank_hero = 8
sprite_chr_group_bank_rushtech = 8
sprite_chr_group_bank_fetchtech = 8
sprite_chr_group_bank_unlocktech = 8
sprite_chr_group_bank_bombtech = 8
sprite_chr_group_bank_lanterntech = 8
sprite_chr_group_bank_carrytech = 8
sprite_chr_group_bank_shieldtech = 8
sprite_chr_group_bank_homingtech = 8
sprite_chr_group_bank_familiar = 8
sprite_chr_group_bank_tyto = 8
sprite_chr_group_bank_explosion = 8
sprite_chr_group_bank_shadowspot = 8
sprite_chr_group_bank_bomb = 8
sprite_chr_group_bank_octopus = 8
sprite_chr_group_bank_npcman = 8
sprite_chr_group_bank_npcwoman = 8
sprite_chr_group_bank_key = 8
sprite_chr_group_bank_treasure_chest = 8
sprite_chr_group_bank_cursor = 8
sprite_chr_group_bank_lantern = 8
sprite_chr_group_bank_coins = 8
sprite_chr_group_bank_title = 8
sprite_chr_group_bank_pufferfish = 8
sprite_chr_group_bank_crab = 8
sprite_chr_group_bank_anglerfish = 8
sprite_chr_group_bank_spotlight = 8
sprite_chr_group_bank_octoboss = 8
sprite_chr_group_bank_splash = 8
sprite_chr_group_bank_silmaran = 8
sprite_chr_group_bank_greathornedowl = 8
sprite_chr_group_bank_cage = 8
sprite_chr_group_bank_dungeon_entrance_statue = 8
sprite_chr_group_bank_eel = 8
sprite_chr_group_bank_jellyfish = 8
sprite_chr_group_bank_urchin = 8
sprite_chr_group_bank_ice_shards = 8
sprite_chr_group_bank_ice_block = 8
sprite_chr_group_bank_swordfish_boss = 8
sprite_chr_group_bank_siberianeagleowl = 8
sprite_chr_group_bank_horseshoe_crab = 8
sprite_chr_group_bank_seahorse = 8
sprite_chr_group_bank_intro_cut_scene_great_owls = 8
sprite_chr_group_bank_intro_cut_scene_mermon_leer = 8

.endif
