.ifndef SPRITES_AND_ANIMATIONS_DATA_INC
SPRITES_AND_ANIMATIONS_DATA_INC = 1

.global WalkUp
.global WalkDown
.global WalkSide
.global FightSide
.global FightDown
.global FightUp

.global FamiliarFlySide
.global FamiliarFlyDown
.global FamiliarFlyUp

.global JellyFishFloat
.global JellyFishAttack

.global Explosion

.global NpcManWalkSide
.global NpcManWalkDown
.global NpcManWalkUp

.global NpcWomanWalkDown
.global NpcWomanWalkUp
.global NpcWomanWalkSide

.global Key

.endif
