.ifndef SPRITES_AND_ANIMATIONS_DATA_INC
SPRITES_AND_ANIMATIONS_DATA_INC = 1

SPRITES_AND_ANIMATIONS_DATA_BANK1 = 6

.global adlanniel_walk_up
.global adlanniel_walk_down
.global adlanniel_walk_side
.global adlanniel_fight_side
.global adlanniel_fight_down
.global adlanniel_fight_up
.global adlanniel_throw_side
.global adlanniel_throw_up
.global adlanniel_throw_down

.global heart0
.global heart

.global Tech0

.global FamiliarFlySide
.global FamiliarFlyDown
.global FamiliarFlyUp

.global OctopusFly

.global Explosion

.global NpcManWalkSide
.global NpcManWalkDown
.global NpcManWalkUp

.global NpcWomanWalkDown
.global NpcWomanWalkUp
.global NpcWomanWalkSide

.global Key
.global KeyInserted

.global Cursor0
.global Radio0

.global Bomb0
.global Bomb

.global Lantern0
.global Lantern

.global Rope0
.global Rope

.global Coins0
.global Coins

.global OwliaTitle0
.global OwliaTitle1

.global PufferFishPuffedDown
.global PufferFishUnpuffedDown
.global PufferFishUnpuffedUp
.global PufferFishPuffedUp
.global PufferFishPuffedSide
.global PufferFishUnpuffedSide

.global CrabWalk0
.global CrabWalk1
.global CrabWalk2

.global CrabWalk

.global AnglerFishUp0
.global AnglerFishUp1
.global AnglerFishDown0
.global AnglerFishDown1
.global AnglerFishSide0
.global AnglerFishSide2

.global AnglerFishUp
.global AnglerFishDown
.global AnglerFishSide

.global SpotLight0

.global SpotLight

.global OctobossHead
.global OctobossLegsDangle
.global OctobossRise
.global OctobossHeadLook
.global OctobossLegsPunch

.global Splash

.global TytoWake0
.global TytoWake1
.global TytoWake2

.global TytoWake

.global SilmaranDescend0
.global SilmaranDescend1
.global SilmaranDescend2
.global SilmaranPerch0

.global SilmaranDescend
.global SilmaranPerch

.global GreatHornedOwlFly0
.global GreatHornedOwlFly1
.global GreatHornedOwlFly2
.global GreatHornedOwlInsideCage0
.global GreatHornedOwlOutsideCage0

.global GreatHornedOwlInsideCage
.global GreatHornedOwlOutsideCage
.global GreatHornedOwlFly

.global Cage

.global OwlEyes0
.global OwlEyes1

.global CagedOwlEyes0
.global CagedOwlCage0

.endif
