.ifndef SPRITES_AND_ANIMATIONS_DATA_INC
SPRITES_AND_ANIMATIONS_DATA_INC = 1

.global WalkUp0
.global WalkUp1
.global WalkDown0
.global WalkDown1
.global WalkSide0
.global WalkSide1
.global FightSide0
.global FightSide1
.global FightDown0
.global FightDown1
.global FightUp0
.global FightUp1

.global WalkUp
.global WalkDown
.global WalkSide
.global FightSide
.global FightDown
.global FightUp

.global FamiliarFly0
.global FamiliarFly1
.global FamiliarFly2

.global FamiliarFly

.global TigerWalkSide0
.global TigerWalkSide1
.global TigerWalkUp0
.global TigerWalkUp1
.global TigerWalkDown0
.global TigerWalkDown1

.global TigerWalkSide
.global TigerWalkUp
.global TigerWalkDown

.global explosion0
.global explosion1
.global explosion2

.global Explosion

.global NpcManWalkSide0
.global NpcManWalkSide1
.global NpcManWalkDown0
.global NpcManWalkDown1
.global NpcManWalkUp0
.global NpcManWalkUp1

.global NpcManWalkSide
.global NpcManWalkDown
.global NpcManWalkUp

.global NpcWomanWalkDown0
.global NpcWomanWalkDown1
.global NpcWomanWalkUp0
.global NpcWomanWalkUp1
.global NpcWomanWalkSide0
.global NpcWomanWalkSide1

.global NpcWomanWalkDown
.global NpcWomanWalkUp
.global NpcWomanWalkSide

.endif
