.ifndef SPRITE_CHR_INC
SPRITE_CHR_INC = 1

.global sprite_chr_group_addresses_lo
.global sprite_chr_group_addresses_hi

.global hero_chr
.global Familiar_chr
.global JellyFish_chr
.global explosion_chr
.global NpcMan_chr
.global NpcWoman_chr

.enum
sprite_chr_group_index_hero
sprite_chr_group_index_familiar
sprite_chr_group_index_explosion
sprite_chr_group_index_jellyfish
sprite_chr_group_index_npcman
sprite_chr_group_index_npcwoman
.endenum

.endif
