metatile_table_properties:
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($00 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($00 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($00 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($00 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($00 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($00 | ACTION_GOTO_LOCATION_GROUP1)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($00 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($00 | ACTION_NOP)
metatile_table_params:
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte location_index_piratebay_piratetavern_entrance1
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
metatile_table_attributes:
  .byte $00,$11,$11,$00,$22,$00,$22,$00,$11,$00,$11,$22,$00,$11,$00,$22,$00,$11,$11,$00,$22,$11,$11,$11
  .byte $11,$00,$00,$11,$00,$11,$11,$00,$11,$00,$11,$11,$22,$11,$00,$22,$00,$11,$22,$11,$11,$00,$11,$11
  .byte $11
metatile_table_top_left_tiles:
  .byte $26,$03,$c8,$28,$97,$46,$8d,$54,$ad,$00,$30,$8f,$28,$63,$1d,$61,$26,$bf,$52,$48,$95,$23,$5a,$01
  .byte $04,$42,$21,$c7,$00,$0e,$cc,$2e,$60,$1f,$34,$73,$93,$03,$35,$91,$6f,$b1,$b3,$10,$32,$44,$60,$1b
  .byte $c3
metatile_table_top_right_tiles:
  .byte $27,$02,$c9,$29,$98,$47,$8e,$55,$ae,$00,$31,$90,$29,$60,$1e,$62,$27,$c0,$53,$49,$96,$24,$5b,$02
  .byte $05,$43,$22,$c6,$00,$0f,$c6,$2f,$60,$20,$1b,$74,$94,$02,$36,$92,$70,$b2,$b4,$10,$33,$45,$64,$1c
  .byte $c4
metatile_table_bottom_left_tiles:
  .byte $3a,$08,$cf,$3c,$a9,$4e,$9f,$58,$b7,$00,$25,$a1,$28,$6c,$26,$6a,$26,$c1,$56,$50,$a7,$2c,$65,$06
  .byte $0c,$4a,$2a,$cf,$00,$13,$cf,$2e,$69,$28,$39,$7f,$a5,$0a,$3e,$a3,$7b,$b9,$bb,$15,$25,$4c,$69,$25
  .byte $65
metatile_table_bottom_right_tiles:
  .byte $3b,$09,$d0,$3d,$aa,$4f,$a0,$59,$b8,$00,$1b,$a2,$29,$6d,$27,$6b,$27,$c2,$57,$51,$a8,$2d,$66,$07
  .byte $0d,$4b,$2b,$d0,$00,$14,$d0,$2f,$69,$29,$39,$80,$a6,$0b,$3f,$a4,$7c,$ba,$bc,$16,$1b,$4d,$6e,$1b
  .byte $66
big_metatile_table_top_left:
  .byte $2a,$2a,$2f,$13,$29,$2f,$14,$2d,$2d,$2d,$2d,$2d,$2d,$00,$22,$24,$17,$1d,$13,$22,$2d,$2d,$26,$2d
  .byte $22,$14,$15,$22,$2d,$09,$2d,$1d,$1d,$1d,$22,$2f,$14,$08,$1d,$2d,$01,$28,$23,$13,$0e,$30,$13,$1a
  .byte $07,$2d,$2d,$18,$22,$1d,$2f,$2f,$22,$16,$01
big_metatile_table_top_right:
  .byte $08,$22,$1d,$13,$2a,$2f,$14,$12,$2d,$16,$2d,$2d,$2a,$03,$22,$14,$01,$19,$13,$22,$2d,$2d,$22,$30
  .byte $22,$14,$15,$1d,$2d,$09,$2d,$09,$2f,$09,$22,$2f,$04,$29,$19,$2b,$25,$23,$2d,$13,$21,$2d,$13,$2f
  .byte $13,$28,$2d,$09,$09,$22,$2f,$09,$22,$1d,$01
big_metatile_table_bottom_left:
  .byte $2d,$2d,$2f,$20,$11,$2c,$2d,$2d,$2d,$2d,$02,$2d,$2d,$2d,$09,$2d,$1d,$1d,$0f,$2d,$1e,$2d,$2d,$1b
  .byte $2d,$2d,$0a,$12,$1b,$09,$02,$1b,$1d,$1d,$13,$2f,$2d,$2d,$1b,$06,$2b,$27,$0b,$20,$10,$02,$20,$1f
  .byte $0d,$06,$1c,$1d,$09,$1d,$2f,$2f,$07,$2d,$2b
big_metatile_table_bottom_right:
  .byte $2d,$2d,$1d,$0f,$2d,$2f,$06,$16,$11,$2d,$02,$2d,$2d,$2d,$09,$06,$2b,$19,$0f,$2d,$02,$06,$2d,$1e
  .byte $12,$2d,$0a,$1d,$02,$09,$1e,$09,$2f,$09,$05,$0a,$2d,$2d,$1b,$2f,$1d,$0b,$06,$2e,$0c,$02,$20,$2f
  .byte $0f,$27,$1c,$09,$09,$19,$2f,$09,$05,$1d,$2b
map:
  .byte $10,$3a,$3a,$3a,$3a,$28,$3a,$3a,$3a,$3a,$3a,$33,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$20,$2c,$2f,$36,$36,$02,$36,$23,$1a,$1a,$05,$21,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$35,$0d,$16,$18,$13,$1b,$38,$22
  .byte $22,$22,$22,$21,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $11,$07,$0b,$09,$0b,$39,$30,$2e,$03,$12,$2b,$21,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$11,$31,$2a,$15,$29,$27,$0f,$19,$06,$06,$24,$21,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$11,$00,$04,$0c,$25,$01,$0c,$0b
  .byte $0c,$0c,$08,$21,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $26,$1c,$2d,$0a,$0a,$0b,$14,$0a,$0a,$1e,$17,$1f,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$36,$36,$36,$36,$36,$0b,$36,$36,$36,$36,$36,$37,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$0e,$0e,$0e,$0e,$0e,$32,$0e,$0e
  .byte $0e,$0e,$0e,$34,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
  .byte $1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d,$1d
