metatile_table_properties:
  .byte ($00 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($00 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($00 | ACTION_GOTO_LOCATION_GROUP1)
  .byte ($00 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($00 | ACTION_GOTO_LOCATION_GROUP1)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($00 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($00 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
metatile_table_params:
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte location_index_piratebay_piratetavern_entrance2
  .byte $00
  .byte $00
  .byte location_index_piratebay_piratetavern_entrance1
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
metatile_table_attributes:
  .byte $00,$22,$11,$33,$33,$22,$22,$22,$33,$22,$11,$11,$22,$11,$11,$22,$22,$11,$00,$22,$22,$00,$22,$11
  .byte $22,$11,$22,$11,$22,$22,$11,$22,$11,$33,$22,$11,$22,$33,$22,$22,$33,$11,$22,$22,$11,$11,$33,$33
  .byte $33,$22,$33,$11,$22,$22,$33,$22,$11
metatile_table_top_left_tiles:
  .byte $10,$9c,$6f,$3b,$bf,$59,$1e,$81,$47,$5a,$67,$6d,$5e,$7d,$26,$30,$a8,$6d,$10,$cb,$bd,$10,$9e,$b0
  .byte $cd,$24,$1b,$75,$98,$0d,$7f,$02,$6b,$49,$02,$96,$31,$45,$ac,$0f,$ae,$24,$03,$bb,$73,$94,$39,$cf
  .byte $3d,$aa,$c1,$6f,$00,$30,$9a,$85,$69
metatile_table_top_right_tiles:
  .byte $10,$9d,$70,$3c,$c0,$58,$1b,$82,$48,$5b,$68,$6e,$58,$7e,$27,$32,$a9,$6e,$10,$cc,$be,$10,$9f,$b1
  .byte $ce,$25,$1c,$76,$99,$0e,$80,$01,$6c,$4a,$01,$97,$30,$46,$ad,$0f,$af,$25,$04,$bc,$74,$95,$3a,$d0
  .byte $3e,$ab,$c2,$70,$01,$30,$9b,$86,$6a
metatile_table_bottom_left_tiles:
  .byte $10,$93,$6f,$41,$c7,$61,$21,$8d,$4d,$61,$6d,$77,$61,$89,$2a,$35,$b3,$6d,$10,$d1,$c5,$10,$93,$b9
  .byte $d1,$28,$1d,$7b,$a4,$13,$8b,$07,$71,$4f,$09,$a2,$36,$4b,$b5,$15,$b7,$28,$0b,$c3,$73,$a0,$3f,$d3
  .byte $43,$b5,$c9,$79,$05,$35,$a6,$91,$6f
metatile_table_bottom_right_tiles:
  .byte $10,$87,$70,$42,$c8,$62,$21,$8e,$4e,$62,$6e,$78,$62,$8a,$2b,$38,$b4,$6e,$10,$d2,$c6,$10,$87,$ba
  .byte $d2,$29,$1b,$7c,$a5,$14,$8c,$08,$72,$50,$0a,$a3,$37,$4c,$b6,$16,$b8,$29,$0c,$c4,$74,$a1,$40,$d4
  .byte $44,$b4,$ca,$7a,$06,$35,$a7,$92,$70
big_metatile_table_top_left:
  .byte $0d,$2d,$1d,$0e,$02,$1d,$0e,$23,$2a,$06,$03,$1a,$1f,$1b,$03,$0e,$00,$37,$18,$0e,$1f,$1d,$12,$08
  .byte $13,$06,$1a,$11,$1a,$2e,$1f,$1a,$0d,$10,$28,$06,$1d,$26,$08,$0e,$05,$06,$07,$1d,$0e,$00,$08,$0e
  .byte $1d,$1f,$28,$0e,$0b,$09,$0e,$0e,$0e,$0c,$0e,$0e,$1d,$1d,$0e,$0e,$1a,$0e,$0e,$0e,$0e,$0e,$25,$30
  .byte $0e,$1a,$34,$1f,$1a,$0a,$0e,$1f,$1e,$0e,$09,$06,$34,$0e,$36,$06,$0e,$1d,$0e,$2c,$05,$20
big_metatile_table_top_right:
  .byte $07,$23,$00,$0e,$2c,$06,$0e,$1c,$00,$06,$30,$0e,$1f,$06,$03,$27,$12,$37,$0e,$1d,$1f,$29,$00,$08
  .byte $1d,$06,$1a,$02,$1d,$03,$1f,$1a,$1e,$26,$06,$06,$1a,$28,$21,$0e,$05,$00,$0e,$2e,$0e,$00,$08,$0e
  .byte $11,$1f,$10,$0e,$33,$09,$09,$0e,$1a,$05,$0e,$0e,$29,$29,$0e,$13,$1a,$0e,$0e,$2b,$0e,$1d,$08,$1d
  .byte $0e,$1a,$1f,$2a,$00,$38,$36,$22,$07,$0e,$0e,$1d,$1f,$0d,$0e,$06,$18,$00,$28,$1d,$09,$1a
big_metatile_table_bottom_left:
  .byte $32,$10,$05,$35,$33,$1d,$09,$31,$1d,$0e,$08,$06,$27,$0e,$08,$36,$00,$01,$09,$0e,$38,$1d,$00,$0e
  .byte $0e,$00,$1a,$0b,$1a,$25,$0a,$16,$2d,$0e,$0e,$0e,$1d,$14,$0e,$24,$1a,$00,$04,$1d,$35,$00,$0e,$0e
  .byte $1d,$1a,$0e,$0e,$0e,$1a,$0e,$2f,$0e,$1a,$0c,$0e,$1d,$05,$35,$0e,$1a,$05,$24,$0e,$09,$0f,$0e,$21
  .byte $15,$06,$1d,$20,$1a,$11,$0e,$27,$23,$2f,$1a,$2b,$1d,$36,$0e,$0e,$05,$1d,$0e,$1b,$1a,$2c
big_metatile_table_bottom_right:
  .byte $04,$31,$00,$2f,$1b,$19,$0c,$26,$00,$17,$21,$0e,$27,$0e,$08,$1a,$00,$01,$09,$1d,$20,$29,$00,$0e
  .byte $1d,$00,$01,$33,$1d,$08,$38,$1a,$23,$0e,$0e,$0e,$1a,$0e,$0e,$35,$1a,$00,$36,$25,$0f,$00,$36,$14
  .byte $0b,$1a,$0e,$0e,$0e,$1a,$1a,$2f,$06,$1a,$09,$36,$24,$05,$35,$0e,$1a,$09,$2f,$13,$09,$1d,$36,$1d
  .byte $15,$06,$27,$1d,$00,$02,$0e,$1d,$1c,$35,$0e,$1d,$0a,$32,$0e,$2b,$0c,$00,$0e,$1d,$1a,$1a
map:
  .byte $4a,$0c,$0c,$0c,$0c,$4f,$0c,$0c,$0c,$0c,$0c,$08,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $54,$14,$31,$31,$31,$31,$1e,$4b,$24,$4d,$5d,$40,$40,$1c,$40,$1a,$11,$11,$1f,$59,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$30,$04,$49,$49,$49,$49,$1b,$5b,$05,$34,$0d,$57,$23,$53,$09,$09
  .byte $09,$09,$09,$59,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$3c,$3e,$2c,$20,$50,$27,$51,$45
  .byte $15,$43,$33,$3f,$33,$18,$42,$3e,$03,$37,$2c,$59,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2b,$0e,$0a,$01,$07,$1d,$0e,$47,$15,$55,$2a,$3b,$00,$0f,$46,$17,$2e,$2e,$26,$59,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$15,$56,$33,$33,$33,$33,$4e,$13,$15,$32,$25,$5a,$21,$22,$5a,$33
  .byte $5a,$5a,$2f,$59,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$28,$28,$5c,$52,$36,$35,$39,$39
  .byte $3d,$41,$12,$44,$44,$33,$3a,$44,$44,$06,$58,$02,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $49,$49,$49,$0b,$38,$49,$49,$49,$40,$40,$40,$40,$40,$33,$40,$40,$40,$40,$40,$4c,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$10,$16,$2d,$2d,$2d,$19,$19,$19,$19,$19,$48,$19,$19
  .byte $19,$19,$19,$29,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
  .byte $2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d,$2d
