metatile_table_properties:
  .byte ($00 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($00 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($00 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($00 | ACTION_GOTO_LOCATION_GROUP1)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($00 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($00 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($00 | ACTION_GOTO_LOCATION_GROUP1)
metatile_table_params:
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte location_index_piratebay_piratetavern_entrance1
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte location_index_piratebay_piratetavern_entrance2
metatile_table_attributes:
  .byte $00,$22,$11,$33,$33,$22,$22,$22,$33,$22,$11,$11,$22,$11,$11,$22,$22,$11,$22,$22,$00,$22,$11,$22
  .byte $22,$11,$22,$22,$11,$22,$11,$33,$22,$11,$22,$33,$22,$22,$33,$11,$22,$22,$11,$11,$33,$33,$33,$22
  .byte $33,$11,$22,$22,$33,$22,$11,$00
metatile_table_top_left_tiles:
  .byte $10,$9c,$6f,$3b,$bf,$59,$1e,$81,$47,$5a,$67,$6d,$5e,$7d,$26,$30,$a8,$6d,$cb,$bd,$10,$9e,$b0,$cd
  .byte $1b,$75,$98,$0d,$7f,$02,$6b,$49,$02,$96,$31,$45,$ac,$0f,$ae,$24,$03,$bb,$73,$94,$39,$cf,$3d,$aa
  .byte $c1,$6f,$00,$30,$9a,$85,$69,$10
metatile_table_top_right_tiles:
  .byte $10,$9d,$70,$3c,$c0,$58,$1b,$82,$48,$5b,$68,$6e,$58,$7e,$27,$32,$a9,$6e,$cc,$be,$10,$9f,$b1,$ce
  .byte $1c,$76,$99,$0e,$80,$01,$6c,$4a,$01,$97,$30,$46,$ad,$0f,$af,$25,$04,$bc,$74,$95,$3a,$d0,$3e,$ab
  .byte $c2,$70,$01,$30,$9b,$86,$6a,$10
metatile_table_bottom_left_tiles:
  .byte $10,$93,$6f,$41,$c7,$61,$21,$8d,$4d,$61,$6d,$77,$61,$89,$2a,$35,$b3,$6d,$d1,$c5,$10,$93,$b9,$d1
  .byte $1d,$7b,$a4,$13,$8b,$07,$71,$4f,$09,$a2,$36,$4b,$b5,$15,$b7,$28,$0b,$c3,$73,$a0,$3f,$d3,$43,$b5
  .byte $c9,$79,$05,$35,$a6,$91,$6f,$10
metatile_table_bottom_right_tiles:
  .byte $10,$87,$70,$42,$c8,$62,$21,$8e,$4e,$62,$6e,$78,$62,$8a,$2b,$38,$b4,$6e,$d2,$c6,$10,$87,$ba,$d2
  .byte $1b,$7c,$a5,$14,$8c,$08,$72,$50,$0a,$a3,$37,$4c,$b6,$16,$b8,$29,$0c,$c4,$74,$a1,$40,$d4,$44,$b4
  .byte $ca,$7a,$06,$35,$a7,$92,$70,$10
big_metatile_table_top_left:
  .byte $35,$0d,$0e,$10,$31,$1d,$2d,$0e,$2b,$0e,$33,$0e,$18,$1b,$32,$17,$0b,$06,$06,$1b,$19,$18,$08,$06
  .byte $0e,$1b,$26,$23,$1b,$10,$0e,$0e,$06,$1b,$1b,$0e,$0e,$0e,$06,$06,$26,$18,$06,$1d,$00,$0a,$18,$0e
  .byte $0e,$0e,$1f,$0e,$0e,$1b,$06,$0e,$1d,$19,$18,$26,$0f,$0e,$33,$1b,$1e,$0e,$0e,$1e,$28,$0e,$06,$08
  .byte $23,$08,$07,$2f,$22,$08,$36,$13,$1b,$24,$0e,$18,$0e,$12,$0e,$1b,$21,$0e,$0e,$0e
big_metatile_table_top_right:
  .byte $35,$07,$0e,$24,$19,$20,$33,$0e,$21,$0e,$0f,$0e,$0e,$18,$1d,$0e,$31,$06,$06,$23,$06,$18,$08,$06
  .byte $0e,$27,$06,$08,$27,$2f,$0e,$12,$06,$0b,$22,$17,$25,$0e,$00,$06,$0e,$00,$0e,$28,$00,$36,$18,$29
  .byte $0e,$0e,$1b,$1b,$18,$00,$06,$0e,$1d,$1b,$1b,$10,$1b,$0e,$33,$00,$1b,$0e,$06,$18,$00,$0e,$1b,$1f
  .byte $08,$08,$0e,$24,$33,$08,$1e,$1b,$0a,$26,$0e,$18,$0e,$1b,$0e,$06,$1a,$0d,$26,$0e
big_metatile_table_bottom_left:
  .byte $01,$30,$09,$0e,$0e,$25,$03,$33,$2b,$0e,$03,$2d,$18,$1b,$1b,$09,$0e,$1c,$0e,$1b,$0e,$18,$0e,$00
  .byte $14,$05,$0e,$0e,$1b,$0e,$33,$0e,$0e,$1b,$1b,$05,$34,$09,$00,$0e,$0e,$18,$00,$25,$00,$11,$15,$0e
  .byte $0e,$22,$0e,$0c,$0e,$1b,$0d,$0c,$25,$0e,$18,$0e,$2e,$05,$03,$05,$2a,$05,$37,$2a,$1b,$09,$29,$0e
  .byte $0e,$34,$04,$0e,$2c,$0e,$02,$17,$1b,$13,$0e,$18,$0c,$0e,$0e,$1b,$21,$34,$0e,$33
big_metatile_table_bottom_right:
  .byte $01,$04,$0c,$0e,$0e,$1b,$03,$0f,$21,$13,$2e,$2d,$0e,$18,$25,$09,$0e,$07,$29,$27,$0e,$18,$0e,$00
  .byte $14,$05,$0e,$0e,$27,$0e,$33,$0e,$0e,$27,$2c,$0c,$18,$0e,$00,$16,$0e,$00,$37,$1b,$00,$02,$18,$12
  .byte $0e,$2d,$1b,$05,$18,$00,$1c,$09,$25,$1b,$1b,$0e,$1b,$05,$03,$00,$1b,$09,$00,$18,$00,$09,$1b,$0e
  .byte $34,$0e,$34,$0e,$03,$34,$2a,$1b,$11,$0e,$09,$01,$05,$1b,$34,$27,$1a,$30,$0e,$2d
map:
  .byte $0e,$38,$38,$38,$38,$05,$38,$38,$38,$38,$38,$44,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $0e,$38,$38,$38,$38,$38,$38,$2b,$0d,$2d,$43,$15,$15,$3a,$15,$53,$00,$00,$2e,$35,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$50,$4e,$15,$15,$15,$15,$2d,$40,$57,$10,$14,$12,$20,$46,$27,$27
  .byte $27,$27,$27,$35,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$21,$04,$20,$36,$11,$20,$10,$39
  .byte $1c,$2f,$30,$1f,$30,$55,$31,$1e,$5b,$0b,$07,$35,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $22,$3e,$0a,$08,$58,$4c,$06,$3c,$1c,$59,$4a,$56,$01,$24,$48,$16,$4d,$4d,$47,$35,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$13,$49,$47,$1d,$4b,$1b,$4d,$32,$1c,$3b,$51,$5a,$03,$1a,$5a,$30
  .byte $5a,$5a,$09,$35,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$1c,$28,$30,$30,$30,$30,$5a,$4f
  .byte $19,$41,$0f,$45,$45,$30,$37,$45,$45,$02,$23,$3f,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $19,$3d,$41,$25,$52,$45,$54,$33,$15,$15,$15,$15,$15,$30,$15,$15,$15,$15,$15,$29,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$15,$15,$15,$0c,$34,$15,$15,$15,$17,$17,$17,$17,$17,$18,$17,$17
  .byte $17,$17,$17,$26,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$17,$17,$17,$2a,$42,$17,$17,$17
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
  .byte $2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c,$2c
