metatile_table_properties:
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_GOTO_LOCATION_GROUP1)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($00 | ACTION_NOP)
  .byte ($00 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_GOTO_LOCATION_GROUP1)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_GOTO_LOCATION_GROUP1)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_GOTO_LOCATION_GROUP1)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($00 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_GOTO_LOCATION_GROUP1)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($00 | ACTION_GOTO_LOCATION_GROUP1)
  .byte ($10 | ACTION_GOTO_LOCATION_GROUP1)
  .byte ($10 | ACTION_NOP)
  .byte ($00 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
  .byte ($10 | ACTION_NOP)
metatile_table_params:
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte location_index_housebl_exit
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte location_index_potionstore_exit
  .byte $00
  .byte location_index_inn_exit
  .byte $00
  .byte location_index_house1_exit
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte location_index_housebr_exit
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte $00
  .byte location_index_meadow1_top_entrance
  .byte location_index_housetr_exit
  .byte $00
  .byte $00
  .byte $00
  .byte $00
metatile_table_attributes:
  .byte $11,$11,$33,$11,$11,$11,$00,$11,$33,$33,$33,$33,$33,$11,$33,$33,$00,$11,$33,$33,$00,$11,$00,$11
  .byte $33,$11,$00,$33,$33,$11,$11,$22,$00,$00,$33,$22,$33,$00,$33,$11,$11,$00,$11,$33,$00,$11,$11,$33
  .byte $00,$33,$11,$11,$11,$11,$11,$33,$33,$33,$11,$22,$33,$33,$33,$33,$00
metatile_table_top_left_tiles:
  .byte $21,$93,$39,$b5,$07,$23,$99,$0f,$77,$48,$45,$62,$52,$ce,$91,$8d,$64,$2d,$47,$74,$97,$00,$7d,$95
  .byte $61,$b5,$7b,$3a,$45,$b3,$ca,$2f,$7e,$68,$91,$3f,$91,$9b,$91,$0d,$50,$3d,$25,$5f,$66,$bb,$ba,$5f
  .byte $89,$91,$0b,$02,$09,$05,$8f,$79,$76,$3b,$8b,$2f,$91,$56,$b8,$37,$b1
metatile_table_top_right_tiles:
  .byte $22,$94,$3a,$b6,$08,$24,$9a,$10,$78,$49,$46,$63,$53,$94,$92,$8e,$65,$2e,$47,$75,$98,$01,$7d,$96
  .byte $49,$b7,$7c,$3a,$5e,$b4,$cb,$30,$7f,$69,$92,$40,$92,$9c,$92,$0e,$51,$3e,$26,$5f,$67,$bc,$b6,$60
  .byte $8a,$92,$0c,$03,$0a,$06,$90,$7a,$76,$3c,$8c,$30,$92,$57,$b9,$38,$b2
metatile_table_bottom_left_tiles:
  .byte $27,$a7,$47,$c1,$17,$29,$ad,$1f,$81,$48,$45,$6c,$54,$d5,$a5,$a1,$6e,$31,$47,$80,$ab,$11,$7d,$a9
  .byte $6b,$c3,$85,$47,$45,$bf,$d0,$33,$87,$72,$a5,$4c,$a5,$af,$a5,$1d,$29,$4a,$2b,$04,$70,$c8,$c6,$04
  .byte $9d,$a5,$1b,$13,$19,$15,$a3,$83,$81,$48,$9f,$33,$a5,$5a,$a5,$45,$bd
metatile_table_bottom_right_tiles:
  .byte $28,$a8,$47,$c2,$18,$2a,$ae,$20,$82,$49,$46,$6d,$55,$a8,$a6,$a2,$6f,$32,$47,$81,$ac,$12,$7d,$aa
  .byte $49,$c4,$86,$47,$6a,$c0,$d1,$34,$88,$73,$a6,$4d,$a6,$b0,$a6,$1e,$2a,$4b,$2c,$04,$71,$c9,$c7,$04
  .byte $9e,$a6,$1c,$14,$1a,$16,$a4,$84,$81,$49,$a0,$34,$a6,$5b,$c5,$46,$be
big_metatile_table_top_left:
  .byte $1f,$23,$1f,$2a,$1f,$30,$29,$38,$06,$29,$18,$29,$2e,$29,$3a,$2b,$2d,$23,$09,$1f,$28,$1f,$36,$1f
  .byte $1f,$29,$12,$12,$19,$08,$1e,$23,$1f,$29,$23,$36,$1e,$23,$36,$0c,$23,$1d,$1f,$29,$29,$2f,$09,$29
  .byte $0f,$2e,$29,$17,$38,$1d,$1f,$1f,$1f,$28,$3f,$12,$06,$29,$1f,$29,$12,$1e,$29,$1f,$1f,$2a,$0a,$19
  .byte $1f,$03,$1e,$23,$2b,$01,$1f,$29,$1b,$0f,$38,$2c,$26,$2c,$12,$1b,$38,$1f,$30,$38,$3d,$16,$16,$0a
  .byte $23,$1e,$1f,$1e,$29,$05,$1f,$1f,$29,$29,$23,$13,$1f,$1f,$39,$1f,$1e,$1c
big_metatile_table_top_right:
  .byte $3a,$1e,$1f,$29,$1f,$1f,$23,$38,$25,$10,$1f,$30,$03,$29,$0f,$2f,$1f,$1e,$1f,$1f,$29,$1f,$3c,$1f
  .byte $29,$29,$0c,$12,$3e,$1f,$1f,$23,$1e,$28,$40,$0e,$23,$29,$31,$12,$29,$03,$1f,$29,$00,$18,$1f,$29
  .byte $36,$03,$00,$1f,$38,$03,$1e,$23,$0a,$28,$02,$12,$06,$29,$1f,$29,$09,$29,$1f,$1c,$1e,$29,$12,$3e
  .byte $1f,$03,$30,$29,$2b,$0f,$23,$29,$1b,$17,$38,$2c,$01,$21,$12,$1b,$38,$1f,$1e,$38,$12,$16,$20,$12
  .byte $1a,$30,$1f,$1e,$14,$05,$1f,$1f,$30,$29,$1f,$38,$28,$1f,$1f,$1f,$1f,$2b
big_metatile_table_bottom_left:
  .byte $1f,$1e,$1b,$34,$04,$1f,$29,$36,$23,$23,$08,$29,$1f,$07,$1d,$38,$1f,$1f,$18,$1e,$11,$1f,$19,$1b
  .byte $1f,$33,$12,$2b,$1f,$17,$1e,$1f,$1f,$29,$1f,$19,$1e,$29,$19,$3d,$23,$1f,$1f,$23,$29,$38,$09,$23
  .byte $03,$30,$29,$2d,$37,$1f,$1e,$1e,$1f,$11,$0a,$2b,$23,$29,$3f,$1e,$12,$1e,$1f,$1f,$1f,$2a,$0a,$30
  .byte $39,$1f,$1e,$33,$38,$2e,$1f,$29,$12,$03,$36,$16,$3e,$16,$12,$0c,$0b,$3b,$1f,$0d,$2b,$16,$16,$1c
  .byte $23,$1e,$04,$1f,$29,$11,$1f,$1e,$1e,$29,$1f,$3a,$3b,$1f,$09,$02,$1e,$13
big_metatile_table_bottom_right:
  .byte $1d,$1e,$1b,$29,$32,$1f,$29,$22,$29,$1a,$1f,$29,$1f,$29,$03,$38,$1f,$1e,$1f,$1e,$29,$29,$3e,$39
  .byte $1f,$33,$3d,$2f,$1e,$1f,$1f,$1f,$1f,$11,$1f,$3e,$1f,$29,$3e,$12,$29,$30,$1f,$23,$00,$08,$1f,$29
  .byte $19,$30,$35,$1f,$0f,$1f,$1e,$1e,$0a,$11,$12,$2b,$23,$29,$02,$1e,$09,$29,$1f,$13,$1e,$29,$12,$1e
  .byte $1f,$1f,$29,$33,$38,$03,$1f,$15,$12,$2d,$24,$16,$2e,$20,$12,$12,$0f,$3b,$1e,$0f,$2b,$16,$20,$2b
  .byte $1a,$1e,$04,$1f,$29,$11,$27,$1f,$1e,$23,$1f,$0f,$11,$3f,$1f,$1b,$1e,$38
map:
  .byte $3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d
  .byte $3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$2f,$3d,$3d,$3d,$69,$3d,$3d,$3d,$3d
  .byte $3d,$2f,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$06,$3d,$2f,$3d,$3d,$3d,$3d,$3d,$25,$3d,$4f,$19,$19,$19,$19
  .byte $19,$19,$19,$19,$19,$19,$19,$19,$19,$19,$19,$19,$19,$19,$19,$19,$4b,$19,$0d,$3d,$3d,$06,$3d,$3d
  .byte $3d,$3d,$3d,$2c,$65,$65,$65,$65,$65,$65,$65,$65,$65,$65,$65,$65,$65,$65,$65,$65,$65,$65,$65,$65
  .byte $65,$65,$45,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$2c,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$2a
  .byte $2a,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$45,$3d,$69,$3d,$3d,$25,$2f,$3d,$3d,$2c,$2a,$2a,$2a,$6d
  .byte $6f,$02,$17,$2a,$15,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$3e,$02,$02,$48,$2a,$2a,$45,$3d,$3d,$3d,$3d,$3d
  .byte $3d,$3d,$25,$2c,$2a,$2a,$2a,$38,$1a,$56,$40,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$46,$27,$56,$2e
  .byte $2a,$2a,$45,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$2c,$2a,$2a,$2a,$43,$4c,$4c,$2d,$2a,$2a,$2a,$2a,$2a
  .byte $2a,$2a,$2a,$2a,$71,$4c,$0f,$0a,$2a,$2a,$45,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$2c,$2a,$2a,$2a,$00
  .byte $30,$54,$51,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$0e,$16,$4d,$33,$2a,$2a,$45,$3d,$2f,$3d,$3d,$3d
  .byte $3d,$3d,$25,$2c,$2a,$2a,$2a,$4e,$1f,$24,$1f,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$44,$2a,$2a
  .byte $2a,$2a,$45,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$2c,$2a,$2a,$2a,$2a,$2a,$70,$13,$13,$13,$13,$13,$13
  .byte $13,$13,$13,$13,$13,$36,$2a,$2a,$2a,$2a,$45,$3d,$3d,$3d,$3d,$3d,$2f,$3d,$3d,$2c,$2a,$2a,$2a,$2a
  .byte $2a,$2a,$2a,$2a,$2a,$2a,$2a,$44,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$45,$3d,$3d,$3d,$3d,$3d
  .byte $3d,$3d,$3d,$2c,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$44,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$2a
  .byte $2a,$2a,$45,$3d,$3d,$06,$3d,$3d,$3d,$3d,$3d,$2c,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$13,$13,$36
  .byte $13,$13,$67,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$45,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$2c,$2a,$2a,$3a,$57
  .byte $50,$50,$50,$6e,$2a,$4a,$3d,$2b,$2f,$0b,$1e,$2a,$3a,$57,$50,$6e,$2a,$2a,$45,$69,$3d,$3d,$3d,$3d
  .byte $3d,$3d,$25,$2c,$2a,$2a,$5f,$5c,$3b,$3b,$1b,$12,$2a,$41,$09,$53,$55,$2f,$1e,$2a,$5f,$5c,$1b,$12
  .byte $2a,$2a,$45,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$2c,$2a,$2a,$6b,$5b,$5b,$52,$34,$1d,$2a,$41,$60,$5d
  .byte $5e,$28,$1e,$2a,$6b,$07,$58,$1d,$2a,$2a,$45,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$2c,$2a,$2a,$35,$49
  .byte $49,$1c,$0c,$10,$2a,$41,$64,$3c,$08,$3d,$1e,$2a,$29,$47,$31,$10,$2a,$2a,$45,$69,$3d,$3d,$25,$3d
  .byte $3d,$3d,$3d,$2c,$2a,$2a,$2a,$2a,$2a,$44,$13,$13,$13,$61,$3f,$3f,$3f,$68,$70,$13,$37,$01,$1f,$2a
  .byte $2a,$2a,$45,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$2c,$2a,$2a,$2a,$2a,$2a,$18,$2a,$2a,$2a,$2a,$2a,$44
  .byte $2a,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$2a,$45,$3d,$3d,$3d,$3d,$3d,$69,$3d,$3d,$2c,$2a,$2a,$2a,$2a
  .byte $3e,$02,$02,$48,$2a,$2a,$2a,$44,$2a,$2a,$2a,$2a,$3e,$02,$02,$48,$2a,$2a,$45,$3d,$3d,$3d,$3d,$3d
  .byte $3d,$3d,$3d,$2c,$2a,$2a,$2a,$2a,$46,$27,$56,$2e,$2a,$2a,$2a,$44,$2a,$2a,$2a,$2a,$46,$27,$56,$2e
  .byte $2a,$2a,$45,$3d,$69,$3d,$3d,$3d,$3d,$3d,$3d,$2c,$2a,$2a,$2a,$2a,$71,$4c,$0f,$0a,$2a,$2a,$2a,$44
  .byte $2a,$2a,$2a,$2a,$71,$4c,$0f,$0a,$2a,$2a,$45,$3d,$3d,$3d,$3d,$3d,$69,$3d,$3d,$2c,$2a,$2a,$2a,$2a
  .byte $0e,$23,$4d,$33,$2a,$2a,$2a,$44,$2a,$2a,$42,$2a,$0e,$26,$4d,$33,$2a,$2a,$45,$3d,$3d,$3d,$3d,$3d
  .byte $3d,$3d,$3d,$2c,$2a,$2a,$2a,$2a,$22,$11,$22,$6a,$2a,$2a,$2a,$44,$2a,$2a,$2a,$2a,$2a,$5a,$05,$2a
  .byte $2a,$2a,$45,$3d,$25,$3d,$3d,$25,$3d,$3d,$3d,$2c,$2a,$2a,$2a,$2a,$2a,$20,$63,$63,$63,$63,$63,$63
  .byte $63,$63,$63,$63,$63,$63,$2a,$2a,$2a,$2a,$45,$3d,$3d,$3d,$3d,$3d,$3d,$2f,$3d,$32,$62,$62,$62,$62
  .byte $62,$62,$62,$62,$62,$62,$04,$2a,$66,$62,$62,$62,$62,$62,$62,$62,$62,$62,$03,$3d,$3d,$3d,$3d,$3d
  .byte $3d,$3d,$3d,$21,$39,$39,$39,$39,$39,$39,$39,$39,$39,$39,$39,$59,$6c,$39,$39,$39,$39,$39,$39,$39
  .byte $39,$39,$14,$3d,$3d,$25,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$2f,$3d,$3d,$3d,$3d,$25,$3d,$3d
  .byte $3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d
  .byte $3d,$2f,$3d,$06,$3d,$3d,$3d,$3d,$3d,$69,$3d,$3d,$3d,$3d,$25,$3d,$3d,$2f,$3d,$3d,$3d,$3d,$06,$3d
  .byte $3d,$06,$3d,$3d,$3d,$06,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$69,$3d,$3d,$3d,$3d,$3d,$06,$3d,$3d,$3d,$3d
  .byte $3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d
  .byte $3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$25,$3d,$3d,$3d,$3d,$3d,$3d
