.include "sprites_and_animations_data.inc"

.segment "ROM00"

.include "hero_sprites_and_animations.inc"
.include "familiar_sprites_and_animations.inc"
.include "jellyfish_sprites_and_animations.inc"
.include "explosion_sprites_and_animations.inc"
.include "bomb_sprites_and_animations.inc"
.include "npcman_sprites_and_animations.inc"
.include "npcwoman_sprites_and_animations.inc"
.include "key_sprites_and_animations.inc"
.include "inventory_sprites_and_animations.inc"
.include "keyeddoor_sprites_and_animations.inc"
.include "lantern_sprites_and_animations.inc"
